### ISSUE TITLE
Toggling shape keys?

### ISSUE THREAD

**Issue by oz123** [vladmandic/human-three-vrm#6]
Hi! Thanks for putting this project for others to use! 
I have a VRM model based on Victoria which supports Shape Keys.

Here you can see the lid - which can be toggled - closed:
![Screenshot from 2022-11-16 22-58-03](https://user-images.githubusercontent.com/1083045/202303380-e1089dd6-9571-489c-b636-b1950cdcceae.png)
And opend:
![Screenshot from 2022-11-16 22-56-29](https://user-images.githubusercontent.com/1083045/202303103-e530a7c8-4cd2-4b5b-861a-7e93ac5cdf34.png)

When I load this model using this demo project, the lid is starts open, it then closes, and opens just to stay always open. I have a working VRM file exported from blender, which loads fine (lid closed) using the [dnd demo of three-vrm ](https://pixiv.github.io/three-vrm/packages/three-vrm/examples/dnd.html).
So I am guessing that ,  when you load the model the shape key is somehow toggled. Can you maybe give me a hint?

**Comment by vladmandic** [comment]
this demo appends entire scene definition from a VRM file (`vrm.scene`), not just vrm model itself (`vrm.humanoid`)
(and if some other demo app doesn't append entire scene, but only model itself then animations don't get loaded)

```js
vrm = await loadVRM(model); // load vrm model
scene.add(vrm.scene); // add model to scene
if (!vrm.humanoid) return;
```

so its most likely that VRM model you're using has some animations pre-set along VRM model itself  
you can either  
a) remove them in blender and save vrm model without them or  
b) delete them after vrm file is loaded and before its appended to scene or  
c) disable them in scene itself once they are loaded

**Comment by vladmandic** [comment]
closing as its not a product issue, but feel free to post further on this thread with any additional questions.
